name: Deploy Storybook

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Importante para monorepos

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install  # Mude de 'npm ci' para 'npm install'

      - name: Build Storybook
        run: npm run build

      - name: Deploy
        working-directory: packages/docs
        run: |
          npm install -g gh-pages
          npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}